---

en-GB:
    ui_unit_verbs_build: Plan
    ui_unit_verbs_build_phase_two: Build
    ui_unit_verbs_salvage: Salvage
    ui_unit_verbs_mine: Mine
    ui_unit_verbs_dismiss: Dismiss
    ui_unit_verbs_repair: Repair
    ui_unit_verbs_tech_up: Advance Tech
    ui_unit_verbs_pick_up: Pick Up
    ui_unit_verbs_drink_h_pot: Drink H-Potion
    ui_unit_verbs_drink_g_pot: Drink G-Potion
    ui_unit_verbs_dimensional_door: Recall
    ui_unit_verbs_buy_artifacts: Buy Artifacts
    ui_unit_verbs_train: Train
    ui_unit_verbs_cancel_recruit: Cancel Recruitment
    ui_unit_verbs_cancel_upgrade: Cancel Upgrade
    ui_unit_verbs_upgrade_land: Upgrade
    groove_name_dimensional_door: Dimensional Door
    groove_description_dimensional_door: A relic from the anicent. Allows the wielder to teleport to a tile beside HQ. 5 turn cooldown
    groove_name_indicate_population: Population
    groove_description_indicate_population: The Current Population
    groove_name_indicate_progress: Progress
    groove_description_indicate_progress: percentage completed on the current action
    structure_name_gold: Gold
    structure_name_gem: Gem
    structure_name_gold_camp: Mining Camp
    structure_name_shop: Shop
    structure_name_blacksmith: Blacksmith
    equipment_name_short_sword: Short Sword
    equipment_name_rare_sword: Sword of Death
    equipment_name_axe: Battle Axe
    equipment_name_dagger: Hidden Dagger
    equipment_name_shield: Round Shield
    equipment_name_rare_shield: Shield of Life
    equipment_name_armor: Plate Armor
    equipment_name_helmet: Great Helm
    equipment_name_health_pot: Health Potion
    equipment_name_groove_pot: Groove Potion
    equipment_name_bow: Hunting Bow
    equipment_name_dimensional_door: Dimensional Door
    unit_name_priest: Priest
    unit_class_name_priest: Healer
    unit_description_barracks: Used to recruit new ground units.
    unit_description_barracks_foundation: Foundation for a barracks. Use a villager to complete building it.
    unit_description_port: Used to recruit new water units.
    unit_description_port_foundation: Foundation for a port. Use a villager to complete building it.
    unit_description_hq: Used to recruit villagers and provides 8 population space. If all HQs are destroyed, the player will be eliminated.
    unit_description_hq_foundation: Foundation for a stronghold. Use a villager to complete building it.
    unit_description_city: Villages provides population space for your troops. Each village adds 4 population space.
    unit_description_city_foundation: Foundation for a village. Use a villager to complete building it.
    unit_description_water_city: Water Villages provides population space for your troops. Each water village adds 4 population space.
    unit_description_water_city_foundation: Foundation for a water village. Use a villager to complete building it.
    unit_description_tower: Used to recruit new air units
    unit_description_tower_foundation: Foundation for a tower. Use a villager to complete building it.
    unit_description_gold: Vaulable resources. Can be mined by constructing a mining camp on top of it and staff it with villagers
    unit_description_gem: Rare Vaulable resources. Can be mined by constructing a mining camp on top of it and staff it with villagers
    unit_description_gold_camp: Mining camp for gold. Garrison with villagers to start mining 50 gold per villager per turn
    unit_description_shop: Shop selling 5 random artifacts. restocks every 5 turns.
    unit_description_blacksmith: Upgrades tier 2 and tier 3 land units
    unit_description_short_sword: Well forged short sword. Increases the wielder's overall damage by 4%
    unit_description_rare_sword: A sword of unknown origin. Increases the wielder's overall damage by 4%, min and max damage by 5%
    unit_description_axe: A double bladed battle axe. Increases the wielder's maximal damage by 5%
    unit_description_dagger: Small and nimble dagger. Increases the wielder's minimal damage by 5%
    unit_description_shield: Small shield made of pure metal. Lower incoming damage by 4%
    unit_description_rare_shield: Shield inbused with essense of Life. Lower incoming damage by 4%, min and max damage by 5%
    unit_description_armor: Full body plated armor. Lower incoming minimal damage by 5%
    unit_description_helmet: Great helm covering the entire head. Lower incoming maximal damage by 5%
    unit_description_health_pot: Filled with weird red goo, increases hp by 25. Cannot be used after moving, does not consume turn.
    unit_description_groove_pot: Filled with weird blue goo, increases groove by 25. Cannot be used after moving, does not consume turn.
    unit_description_bow: A bow used by skilled hunter. Allows the wielder to use ranged attack at half the damage
    unit_description_dimensional_door: A relic from the anicent. Allows the wielder to teleport to a tile beside HQ. 5 turn cooldown
    
    trigger_action_name_modify_experience: "Unit: Modify Experience"
    trigger_action_description_modify_experience: "Modifies selected units' experience by adding to it, subtracting from it or setting it to a specific value."
    trigger_action_readable_modify_experience: "Modify experience of {0} at {1} for {2}: {3} {4} (silent = {5})."
  
    trigger_action_name_modify_rank: "Unit: Modify Rank"
    trigger_action_description_modify_rank: "Modifies selected units' rank by adding to it, subtracting from it or setting it to a specific value."
    trigger_action_readable_modify_rank: "Modify rank of {0} at {1} for {2}: {3} {4} (silent = {5})."
  
    trigger_condition_name_experience: "Unit: Experience"
    trigger_condition_description_experience: "Triggers based on the experience of a certain unit."
    trigger_condition_readable_experience: "Does {0} have {1} {2} of {3} at {4} with {5} {6} experience?"
  
    trigger_condition_name_rank: "Unit: Rank"
    trigger_condition_description_rank: "Triggers based on the rank of a certain unit."
    trigger_condition_readable_rank: "Does {0} have {1} {2} of {3} at {4} with {5} rank {6}?"
  
    trigger_condition_name_on_load: "When: During Loading"
    trigger_condition_description_on_load: "Triggers at the start of a reload back into the game."
    trigger_condition_readable_on_load: "Do you load back into the game?"    
    #Music
    music_name_cyberwave_cinematic: Cyberwave Orchestra ~ Cinematic
    #Codex
    codex_rules_gold_mines: Gold Mines
    codex_rules_gold_mines_title: Gold Mines
    codex_rules_gold_mines_text: "> Mines take x1.3 damage\n> Mines have a finite amount of gold that can be mined from them.\n> When a gold mine is almost empty, a yellow warning will appear over the mine.\n> When a gold mine is completely empty, a red exclamation mark will appear, signaling that gold can no longer be gained from that gold mine.\n> Gold mines have a max of 4000 gold.\n> Gem mines have a max of 3000 gold.\n> You can see what percentage of gold is left based on the gold pile's health percentage"

    codex_rules_tech: Tech
    codex_rules_tech_title: Increasing Tech Level
    codex_rules_tech_text: "> Each player starts at tech level 1.\n> You can upgrade your tech level at your Stronghold with enough gold.\n> The amount of gold it takes to upgrade your tech level increases with each level. The first level costs 500 gold, with an additional 500 gold added for each level after that.\n> The units you can recruit and the buildings your villagers can build are decided by your current tech level.\n> At tech level 1 you can build:\n- Barracks\n- Villages\n- Water Villages\n- Ports\n- Gold and Gem Mines\n> In addition, you can recruit:\n- Villagers\n- Soldiers\n- Dogs\n- Spearmen\n- Barges\n- Mermen\n> At tech level 2 gain the ability to build:\n- Walls\n- Strongholds\n- Towers\n> In addition, you can recruit:\n- Wagons\n- Archers\n- Mages\n- Knights\n- Turtles\n- Harpoonships\n- Balloons\n- Harpies\n> At tech level 3 (MAX) you gain the ability to recuit:\n- Trebuchets\n- Ballistas\n- Giants\n- Witches\n- Dragons"

    codex_rules_building: Building
    codex_rules_building_title: Building Structures
    codex_rules_building_text: "> Villagers can build any structure in the game, provided they have the gold and the tech level to do so.\n> Some structures require multiple actions to build. You can do this with many villagers over one turn or one villager over multiple turns."

    codex_rules_pop_cap: Population
    codex_rules_pop_cap_title: Population Capacity
    codex_rules_pop_cap_text: "> Every player has a set max on the number of units they can recruit. This is called your 'Population Cap.' If your army exceeds this number, you cannot recruit more units.\n> Your Population Cap can be increased by building Villages and extra Strongholds.\n- Each village adds 4 units to your popluation cap.\n- Each Stronghold adds 8 units.\n> You can check your current army size and Population Cap by inspecting your Stronghold. The number under the villager is your Population Cap, and the number above the villager is your current army size.\n> The highest possible Population Cap is 100"

    codex_rules_artifacts: Artifacts
    codex_rules_artifacts_title: Artifacts
    codex_rules_artifacts_text: "> Artifacts are items and weapons that provide attack bonuses and special actions for Commanders, giving an edge in head-to-head combat.\n> Only Commanders can use artifacts, but almost any attack can destroy one.\n> Each Commander can use up to 6 artifacts and can put down artifacts whenever necessary.\n- Daggers add 3% to the minimum damage of an attack\n- Axes add 3% to maximum damage of an attack\n- Sword add 2% to overall damage\n- Enchanted Blades add 2% overall damage, 3% minimal damage and 3% maximal damage\n- Armor reduces minimal damage of incoming attacks by 3%\n- Helmets reduce maximum damage of incoming attacks by 3%\n- Shields reduce overall damage of incoming attacks by 2%\n- Magical Shields reduce overall damage by 2%, minimal damage by 3% and maximum damage by 3%\n- Dimensional Doors allow Commanders to teleport to an empty space by an allied Stronghold. A Dimensional Door can be used once every 5 turns\n- Health Potions (red) recover health by 25%\n- Groove Potions (blue) recover groove charge. The amount gained depends on the groove's charge speed\n- Bows allow Commanders to attack up to 3 tiles away and target water and flying units. Bow attacks deal half of the normal damage."

    codex_rules_shop: Shops
    codex_rules_shop_title: Buying Artifacts
    codex_rules_shop_text: "> Artifacts can be bought by Commanders (and only Commanders) at shops.\n> Shops sell five random artifacts and restock every 5 turns"
    
    codex_rules_blacksmith: Blacksmiths
    codex_rules_blacksmith_title: Blacksmiths
    codex_rules_blacksmith_text: "> Blacksmiths can upgrade land units over the course of multiple turns.\n> Requires Tech level II or higher"

    codex_rules_repair: Repairing
    codex_rules_repair_title: Repairing Structures
    codex_rules_repair_text: "> Villagers can repair structures to improve their sustainability.\n> Repairing restores up to 20% health.\n> The cost of repairing is 10% of the building's original cost.\n> Because structures no longer regenerate health each turn, repairing is the only way for structures to regain health."

    #These override existing rules pages to reflect changes in structures
    codex_rules_income_text: "> Gold Mines and Gem Mines provide an income based on the number of villagers in each mine.\n> Gold mines are worth 80 gold per villager per turn.\n> Gem Mines are worth 120 gold per villager per turn.\n> Each mine can only hold 3 villagers at a time.\n> If a mine is destroyed, all mining villagers die.\n> Starting funds are set on a map-by-map basis."
    codex_rules_capture_text: "> Neutral structures can be captured by any unit with the 'capture' attribute.\n> A captured structure begins with half the health of the unit that captured it.\n> Occupied structures are destroyed and removed from the map when defeated.\n> Military structures will counter-attack when possible.\n> Structures don't regenerate like Commanders do.\n> Structures have a range of functions. Refer to the structure description for more information."
    codex_rules_strongholds_text: "> Strongholds take half damage from all units.\n> If all of a player's Strongholds are destroyed the player loses.\n> Strongholds can recruit villagers for 75 gold each so long as your current popluation is within your popluation cap.\n> Strongholds can increase your tech level if you have enough gold.\n> Strongholds can be built by villagers starting at Tech Level 2."


...