---

unitClasses:
  - id: blacksmith
    name: structure_name_blacksmith
    aiPriority: 4.0
    moveRange: 0
    isStructure: true
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: true
    isNeutraliseable: false
    damageMultiplier: 1.0
    battleUnitCount: 1
    hostileNeutral: false
    garrisonUnit: ""
    movement: land_building
    income: 0
    loadCapacity: 10
    cost: 300
    grooveId: blacksmith
    tags:
      - structure
      - salvageable
    verbs:
      - upgrade_land
      - wait
      
units:
  - class: blacksmith
    faction: neutral
    name: structure_name_blacksmith
    mapAnimation: [units/structures/blacksmith/blacksmith]
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: units/structures/blacksmith/portrait_blacksmith_medium.png
    grabPos: [12, 5]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/city/city_background_full
      farBackground: city_background_full_background_2
      nearBackground: city_background_full_background_1
      foreground: city_background_full_foreground
      keeperPosition: [78, 95]
      leftBannerOffset: [-6, 2]
      rightBannerOffset: [0, 2]

...