---

unitClasses:
  - id: gold
    name: structure_name_gold
    aiPriority: 4.0
    moveRange: 0
    isStructure: true
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: false
    isNeutraliseable: true
    damageMultiplier: 0
    hostileNeutral: true
    movement: land_building
    income: 0
    cost: 5000
    tags:
      - structure
      
units:
  - class: gold
    faction: neutral
    name: structure_name_gold
    mapAnimation: [units/structures/gold_mine_1, units/structures/gold_mine_2, units/structures/gold_mine_3]
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: units/structures/gold_mine_medium.png
    grabPos: [12, 5]
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: background_gold
      farBackground: gold_mine_background_full_0_0
      nearBackground: gold_mine_background_full_0_0
      foreground: gold_mine_background_full_0_0
      keeperPosition: [66, 98]
      leftBannerOffset: [-6, 2]
      rightBannerOffset: [-7, 0]

...