---

unitClasses:
  - id: port_foundation
    name: structure_name_port
    aiPriority: 4.0
    moveRange: 0
    isStructure: true
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: true
    isNeutraliseable: false
    damageMultiplier: 1.3
    battleUnitCount: 1
    hostileNeutral: false
    garrisonUnit: ""
    movement: sea_building
    income: 0
    cost: 300
    tags:
      - structure
      - foundation
      
units:
  - class: port_foundation
    faction: neutral
    name: structure_name_port
    mapAnimation: [units/structures/foundation/map_foundation]
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/port.png
    grabPos: [14, 5]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitWood
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/port/port_background_full
      farBackground: port_background_full_background_2
      nearBackground: port_background_full_background_1
      foreground: port_background_full_foreground
      keeperPosition: [66, 98]
      leftBannerOffset: [-6, 2]
      rightBannerOffset: [-7, 0]

...