---

unitClasses:
  - id: tower_foundation
    name: structure_name_tower
    aiPriority: 4.0
    moveRange: 0
    isStructure: true
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: true
    isNeutraliseable: false
    damageMultiplier: 1.3
    battleUnitCount: 1
    hostileNeutral: false
    garrisonUnit: ""
    movement: land_building
    income: 0
    cost: 250
    tags:
      - structure
      - foundation
      
units:
  - class: tower_foundation
    faction: neutral
    name: structure_name_tower
    mapAnimation: [units/structures/foundation/map_foundation]
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/tower.png
    grabPos: [14, 4]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/tower/tower_background_full
      farBackground: tower_background_full_background_2
      nearBackground: tower_background_full_background_1
      foreground: tower_background_full_foreground
      keeperPosition: [72, 75]
      leftBannerOffset: [0, 0]
      rightBannerOffset: [0, 0]

...