---

weapons:
  - id: emericSpell
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.3
      soldier: 0.95
      villager: 0.95
      spearman: 0.65
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.55
      ballista: 0.6
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      
      warship: 0.55
      harpoonship: 0.45
      turtle: 0.55
      travelboat: 0.6
      merman: 0.95

unitClasses:
  - id: commander_emeric
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: emericSpell
#      - id: bow
        ammo: 5
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
    battleUnitCount: 1
    isCommander: true
    grooveId: cherrystone_defence


units:
  - class: commander_emeric
    faction: cherrystone
    name: character_emeric_name
    mapAnimation: units/commanders/emeric/map_emeric
    battleAnimation: units/commanders/emeric/battle_emeric
    battleAnimationRiver: fx/river_overlay/battle_emeric_river
    smallPortrait: units/commanders/emeric/portrait_emeric_small.png
    mediumPortrait: units/commanders/emeric/portrait_emeric_medium.png
    mapSpeed: 4.0
    skinColour: typeVI
    grabPos: [40, 28]
    deathMoveMin: 0
    deathMoveMax: 0
    sounds:
      attackMap: unitAttack
      attack: emeric/emericAttack
      captureShout: emeric/emericCapture
      attackCommander: emeric/emericCommanderKillAttack
      death: emeric/emericDie
      deathMap: emeric/emericDieGhost
      deathMapNoBattle: emeric/emericDieNoBattle
      run: infantryLightMapEntry
      runMap: infantryLightMapEntry
      firstHit: emeric/emericHit
      hit: hitOrganic
      hitMap: hitOrganic
      groove: emeric/emericGrooveIntro
    attacks:
      - id: closeRange
        hitSpark: fx/bs_stab_attack
        effectDelay: 2.95
        hitDelay: 3.0
        samePanel: true
      - id: primary
        hitSpark: fx/bs_stab_attack
        effect: fx/bs_emeric_attack
        effectDelay: 2.95
        hitDelay: 3.0
        ranged: true
    emotes:
      idle: idle
      surprise: emote_surprise
      positive: emote_positive
      negative: emote_negative
      laugh: emote_laugh
      thinking: emote_thinking
      hypno: emote_hypno
      casting: emote_casting
      idle_river: idle_river
      positive_river: emote_positive_river
      negative_river: emote_negative_river
      thinking_river: emote_thinking_river
      surprise_river: emote_surprise_river
      dance: emote_dance
    shouts:
      emeric_attack1: emeric/emericShoutAttack1
      emeric_attack2: emeric/emericShoutAttack2
      emeric_attack3: emeric/emericShoutAttack3
      emeric_attack4: emeric/emericShoutAttack4
      emeric_cherrystonesdefend: emeric/emericShoutCherrystonesDefendUs
      emeric_educatedchoice: emeric/emericShoutEducatedChoice
      emeric_farewell: emeric/emericShoutFarewell
      emeric_gravemistake: emeric/emericShoutGraveMistake
      emeric_greetings: emeric/emericShoutGreetings
      emeric_hit1: emeric/emericShoutHit1
      emeric_hit2: emeric/emericShoutHit2
      emeric_hit3: emeric/emericShoutHit3
      emeric_hit4: emeric/emericShoutHit4
      emeric_hit5: emeric/emericShoutHit5
      emeric_hmm1: emeric/emericShoutHmm1
      emeric_hmm2: emeric/emericShoutHmm2
      emeric_hmm3: emeric/emericShoutHmm3
      emeric_hmph: emeric/emericShoutHmph
      emeric_iagree: emeric/emericShoutIAgree
      emeric_haveaspell1: emeric/emericShoutIHaveASpell1
      emeric_haveaspell2: emeric/emericShoutIHaveASpell2
      emeric_proudofyou: emeric/emericShoutImProudOfYou
      emeric_soproudofyou: emeric/emericShoutImSoProudOfYou
      emeric_imsorry: emeric/emericShoutImSorry
      emeric_interesting: emeric/emericShoutInteresting
      emeric_itisntsafe: emeric/emericShoutItIsntSafe
      emeric_iwasfoolish: emeric/emericShoutIWasFoolish
      emeric_laugh1: emeric/emericShoutLaugh1
      emeric_laugh2: emeric/emericShoutLaugh2
      emeric_lightningblast: emeric/emericShoutLightningBlast
      emeric_mercival1: emeric/emericShoutMercival
      emeric_mercival2: emeric/emericShoutMercivalDistressed
      emeric_myqueen1: emeric/emericShoutMyQueenDistressed
      emeric_myqueen2: emeric/emericShoutMyQueenProud
      emeric_myqueen3: emeric/emericShoutMyQueenSerious
      emeric_myqueen4: emeric/emericShoutMyQueenSurprised
      emeric_no: emeric/emericShoutNo
      emeric_nodoubt: emeric/emericShoutNoDoubt
      emeric_oops: emeric/emericShoutOops
      emeric_sigh: emeric/emericShoutSigh
      emeric_outmatched: emeric/emericShoutSimplyOutmatched
      emeric_tacticaladvantage: emeric/emericShoutTacticalAdvantage
      emeric_thankyou: emeric/emericShoutThankYou
      emeric_theresnotime: emeric/emericShoutThereIsNoTime
      emeric_dothetrick: emeric/emericShoutThisShouldDoTheTrick
      emeric_shouldbeadvantageous: emeric/emericShoutThisShouldBeAdvantageous
      emeric_shouldprotectus: emeric/emericShoutThisShouldProtectUs
      emeric_verywell: emeric/emericShoutVeryWell
      emeric_wellearned: emeric/emericShoutVictoryWellEarned
      emeric_what: emeric/emericShoutWhat
      emeric_wisedecision: emeric/emericShoutWiseDecision
      emeric_yes1: emeric/emericShoutYes1
      emeric_yes2: emeric/emericShoutYes2
      emeric_yourhighness: emeric/emericShoutYourHighness
      emeric_youshallnotpass: emeric/emericShoutYouShallNotPass
      emeric_ghostlaugh: emeric/emericShoutGhostLaugh
      
    alternativeRuns:
      - id: run_river
        sound: infantryLightRiverMapEntry

    alternativeAttackSounds:
      no_voice: emeric/emericAttackNoVoice

    hidden:
      emotes:
        - idle_river
        - positive_river
        - negative_river
        - thinking_river
        - surprise_river
      shouts:
        - emeric_attack2
        - emeric_hit3
        - emeric_ghostlaugh
      alternativeRuns:
        - run_river
...
