---

modifyingUnitClasses:
  - id: villager
    replace:
        isRecruitable: true
        tags:
            - type.ground.villager
        cost: 75
        aiPriority: 2
    add:
        verbs:
            - build
            - mine
            - repair
            - wait_villager
            - build_phase_two

...
