---

grooves:
  - id: dimensional_door
    name: groove_name_dimensional_door
    description: groove_description_dimensional_door
    maxCharge: 5
    chargePerUse: 5
    verb: dimensional_door
  - id: blacksmith
    name: groove_name_blacksmith
    description: groove_description_blacksmith
    maxCharge: 5
    chargePerUse: 5
    verb: wait
  - id: upgraded_indicator
    name: groove_name_upgraded_indicator
    description: groove_description_upgraded_indicator
    maxCharge: 1
    chargePerUse: 0
    verb: wait
  - id: indicate_population
    name: groove_name_indicate_population
    description: groove_description_indicate_population
    maxCharge: 100
    chargePerUse: 0
    verb: wait
  - id: indication_progress
    name: groove_name_indicate_progress
    description: groove_description_indicate_progress
    maxCharge: 100
    chargePerUse: 0
    verb: wait

...